apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  containers:
    - name: {{ .Values.container.name }}
      image: {{ .Values.container.repository }}:{{ .Values.container.tag }}
      imagePullPolicy: {{.Values.container.pullPolicy}}
      ports:
        - containerPort: {{ .Values.container.port }}
          hostPort: {{ .Values.container.hostPort }}
      args:
        - "-v=5"
        - "-logtostderr"
        - "-kubeproxyinit"
        - "-endpoint=0.0.0.0:8081"
